### ISSUE TITLE
Deploy updated version on PiPy

### ISSUE THREAD

**Issue by jasonmcewen** [astro-informatics/Optimus-Primal#7]

**Comment by CosmoMatt** [comment]
Current wheels setup for python 2, and don't actually work on python 2 (no corresponding distribution found). There are also no auto-install requirements (supposedly one must do this manually which isn't great).

Will update throughout to python 3 on redeploy.
Will add requirements and update the setup.py appropriately.

**Comment by jasonmcewen** [comment]
@CosmoMatt I think this is done now right? Can we close this issue?
